Feature: Add animations to foldable section
QuivrHQ/quivr pull request #2202
Opened 2024-02-17 02:05 UTC by johnfewell

# Description

Refactored the foldable section. The design is inspired by [Material Design's expansion panel](https://m1.material.io/components/expansion-panels.html#). The existing design has the chevron alternating from pointing down to pointing right. This is misleading because there is no subordinate information to the right. Also, this PR animates the arrow and foldable section, creating a delightful experience.

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x]I have performed a self-review of my code
- [x] I have commented hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

## Screenshots (if appropriate):
[expansion.webm](https://github.com/QuivrHQ/quivr/assets/1273463/71ef2c98-c0ed-4374-840e-0bf16bf4da55)

2024-02-18 01:11 UTC, Zewed requested changes

2024-02-18 01:17 UTC, Zewed commented
Nice work :) 
Just need some small changes to be merged :)

2024-02-18 19:44 UTC, johnfewell commented on frontend/lib/components/ui/FoldableSection/FoldableSection.tsx
> +          }`}
Done.

2024-02-18 19:44 UTC, johnfewell commented on frontend/lib/components/ui/FoldableSection/FoldableSection.module.scss
> +  max-height: 200px;
Done.

2024-02-18 19:45 UTC, johnfewell commented on frontend/lib/components/ui/FoldableSection/FoldableSection.module.scss
> +    transition: max-height 0.3s cubic-bezier(0.65, 0.05, 0.36, 1);
Done.

2024-02-18 19:47 UTC, johnfewell commented
@Zewed Thank you for your feedback; the issues have been addressed.

2024-02-20 23:08 UTC, Zewed approved these changes

2024-02-20 23:08 UTC, merged