Fix: Knowledge
QuivrHQ/quivr pull request #2966
Opened 2024-08-07 14:48 UTC by chloedia

# Description
In knowledge table : 

+ Create sql model

+ Field File size in KB

+ Field created_at (added in quivr ?) 

+ Field modified_at (last sync ?) 

+ File_sha1 (out of metadata) and index on it

+ metadata (json format) 

+ #Unique file_name

change extension to mimetype

+ Create knowledge_services (sql alchemy)

+ Modify instacition

2024-08-09 09:10 UTC, AmineDiro requested changes

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/knowledge/service/knowledge_service.py
> +            source_link = f"s3://quivr/{inserted_knowledge_db_instance.brain_id}/{inserted_knowledge_db_instance.id}"
The knowledge service shouldn't have the path logic. or it could have this logic if it has a storage instance.

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/repository/sync.py
> +knowledge_service = get_service(KnowledgeService)()
The injection doesnt work outside FastAPI 😃

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/repository/sync_user.py
> +knowledge_service = get_service(KnowledgeService)()
Dependency injection doesn't work here, The knowledge_service isn't used 🤔

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/utils/syncutils.py
>          # Add knowledge and send_task
REmove the comment. Will be fixed in `fix/syncs-worker`

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/utils/upload.py
> +def compute_sha1(content: bytes):
This function is utility function. Maybe move to quivr_core

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/utils/upload.py
> +    logger.debug(f"(UPLOAD) Adding knowledge {knowledge_to_add}")
Lower case for better parsing

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/utils/upload.py
> +knowledge_service = get_service(KnowledgeService)()
Dependency injection doesn't work outside fastpi

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/sync/utils/upload.py
> +        mime_type=os.path.splitext(
We should use mimetype here. The upload_file from fastAPI does have a `content-type` which is a mimetype

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/brain/service/brain_service.py
> +knowledge_service = get_service(KnowledgeService)()
Dependency injection here doesn't work

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/brain/service/brain_service.py
🔺 knowledge service here is async and is not awaited

2024-08-09 09:10 UTC, AmineDiro commented on backend/api/quivr_api/modules/brain/integrations/Multi_Contract/Brain.py
> +            await self.knowledge_qa.knowledge_service.get_all_knowledge_in_brain(
Function is not async. 

This is catched by linter 100% of the time. Maybe force the linter configuration in IDE

2024-08-12 13:21 UTC, chloedia commented on backend/api/quivr_api/modules/sync/utils/upload.py
add knowledge logic for sync to be defined

2024-08-12 13:29 UTC, chloedia commented on backend/supabase/migrations/20240808141057_knowledge_fix.sql
> +alter table "public"."knowledge" add column "metadata_" jsonb;
I first added it as metadata but it gives an error, apparently i don't have the right to call it metadata so i changed it to metadata_

2024-08-12 13:31 UTC, chloedia commented on backend/supabase/seed.sql
>  --
we can re add it, just we need to change the elements so it matches the new table format

2024-08-12 14:23 UTC, merged